version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: redsquatch-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 981u6k7JQ7pTaE6pL1K9mcJQRxpE7QJTHIcIh8kg5bMLUOp2R18moakapvG4mSRf
      POSTGRES_DB: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - coolify
    expose:
      - "5432"

  redsquatch-api:
    image: node:18.20.8
    container_name: redsquatch-api
    working_dir: /app
    volumes:
      - /root/n8n-docker/redsquatch-api:/app
      - minecraft-bedrock:/data
    command: node index.js
    environment:
      NODE_ENV: production
      DB_HOST: redsquatch-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 981u6k7JQ7pTaE6pL1K9mcJQRxpE7QJTHIcIh8kg5bMLUOp2R18moakapvG4mSRf
      DB_NAME: postgres
      SESSION_SECRET: x7Kp2m0nR9vL4wZj8aYc3bNs6uTh5dEf
      SECURE_COOKIES: "true"
    networks:
      - coolify
    restart: always
    depends_on:
      - postgres
    expose:
      - '3001'

  redsquatch-frontend:
    image: node:18.20.8
    container_name: redsquatch-frontend
    working_dir: /app
    volumes:
      - /root/n8n-docker/redsquatch-site:/app
    command: npm run start
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://api.redsquatch.com
    networks:
      - coolify
    restart: always
    depends_on:
      - redsquatch-api
    expose:
      - '3000'

  minecraft-bedrock:
    image: lomot/minecraft-bedrock:latest
    container_name: minecraft-bedrock
    ports:
      - "19132:19132/udp"
    environment:
      EULA: "TRUE"
      SERVER_NAME: "RedSquatch"
      GAMEMODE: "survival"
      DIFFICULTY: "normal"
      MAX_PLAYERS: "4"
      LEVEL_NAME: "RedSquatch"
      ONLINE_MODE: "true"
      ALLOW_CHEATS: "false"
      ALLOW_LIST: "true"
    volumes:
      - minecraft-bedrock:/data
    restart: always
    networks:
      - coolify

volumes:
  minecraft-bedrock:
    driver: local

networks:
  coolify:
    external: true
